"""new tables for planning, sync, ai, topics and analytics

Revision ID: 0002_new_tables
Revises: 0001_existing_schema_adaptation
Create Date: 2026-09-26 02:21:01.819858

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002_new_tables'
down_revision: str | None = '0001_existing_schema_adaptation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('context_type', sa.String(length=20), server_default=sa.text("'general'"), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('context_label', sa.String(length=300), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("context_type IN ('dsa','lld','hld','general')", name=op.f('ck_ai_conversations_context_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_index('ix_ai_conversations_user_id_context', 'ai_conversations', ['user_id', 'context_type', 'context_id'], unique=False)
    op.create_index('ix_ai_conversations_user_id_updated_at', 'ai_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('ai_rate_limits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'window_start', name=op.f('pk_ai_rate_limits'))
    )
    op.create_index('ix_ai_rate_limits_window_start', 'ai_rate_limits', ['window_start'], unique=False)
    op.create_table('dsa_problems',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), server_default=sa.text("'leetcode'"), nullable=False),
    sa.Column('difficulty', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('primary_topic', sa.String(length=100), nullable=False),
    sa.Column('secondary_topics', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('patterns', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('companies', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('problem_type', sa.String(length=50), server_default=sa.text("'algorithmic'"), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('importance', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy','medium','hard')", name=op.f('ck_dsa_problems_difficulty_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dsa_problems'))
    )
    op.create_index('ix_dsa_problems_companies_gin', 'dsa_problems', ['companies'], unique=False, postgresql_using='gin')
    op.create_index('ix_dsa_problems_difficulty_order_index', 'dsa_problems', ['difficulty', 'order_index'], unique=False)
    op.create_index('ix_dsa_problems_patterns_gin', 'dsa_problems', ['patterns'], unique=False, postgresql_using='gin')
    op.create_index('ix_dsa_problems_primary_topic_order_index', 'dsa_problems', ['primary_topic', 'order_index'], unique=False)
    op.create_index('ix_dsa_problems_slug', 'dsa_problems', ['slug'], unique=True)
    op.create_table('dsa_topics',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), server_default=sa.text("'general'"), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dsa_topics')),
    sa.UniqueConstraint('name', name=op.f('uq_dsa_topics_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_dsa_topics_slug'))
    )
    op.create_table('hld_topics',
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=40), server_default=sa.text("'system_design'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('key_concepts', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), server_default=sa.text("'hard'"), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), server_default=sa.text('90'), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('fundamentals','system_design')", name=op.f('ck_hld_topics_category_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hld_topics')),
    sa.UniqueConstraint('slug', name=op.f('uq_hld_topics_slug'))
    )
    op.create_index('ix_hld_topics_category_order_index', 'hld_topics', ['category', 'order_index'], unique=False)
    op.create_table('lld_topics',
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=40), server_default=sa.text("'fundamentals'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('key_concepts', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('fundamentals','design_patterns','design_exercises')", name=op.f('ck_lld_topics_category_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lld_topics')),
    sa.UniqueConstraint('slug', name=op.f('uq_lld_topics_slug'))
    )
    op.create_index('ix_lld_topics_category_order_index', 'lld_topics', ['category', 'order_index'], unique=False)
    op.create_table('problem_attempts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.String(length=300), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("outcome IN ('gave_up','partial','solved','solved_with_hint','revision_success','revision_failed')", name=op.f('ck_problem_attempts_outcome_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_attempts'))
    )
    op.create_index(op.f('ix_problem_attempts_problem_id'), 'problem_attempts', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_attempts_user_id'), 'problem_attempts', ['user_id'], unique=False)
    op.create_index('ix_problem_attempts_user_id_problem_id_started_at', 'problem_attempts', ['user_id', 'problem_id', 'started_at'], unique=False)
    op.create_index('ix_problem_attempts_user_id_updated_at', 'problem_attempts', ['user_id', 'updated_at'], unique=False)
    op.create_table('sync_changes',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_changes')),
    sa.UniqueConstraint('seq', name=op.f('uq_sync_changes_seq'))
    )
    op.create_index('ix_sync_changes_user_id_entity', 'sync_changes', ['user_id', 'entity'], unique=False)
    op.create_index('ix_sync_changes_user_id_seq', 'sync_changes', ['user_id', 'seq'], unique=False)
    op.create_table('sync_mutations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mutation_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=True),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_mutations')),
    sa.UniqueConstraint('user_id', 'mutation_id', name=op.f('uq_sync_mutations_user_id_mutation_id'))
    )
    op.create_index('ix_sync_mutations_user_id_created_at', 'sync_mutations', ['user_id', 'created_at'], unique=False)
    op.create_table('user_activity_days',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('activity_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('study_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('problems_solved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('problems_attempted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('revisions_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('topics_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity_days')),
    sa.UniqueConstraint('user_id', 'activity_date', name=op.f('uq_user_activity_days_user_id_activity_date'))
    )
    op.create_index(op.f('ix_user_activity_days_user_id'), 'user_activity_days', ['user_id'], unique=False)
    op.create_index('ix_user_activity_days_user_id_activity_date', 'user_activity_days', ['user_id', 'activity_date'], unique=False)
    op.create_table('user_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_identifier', sa.String(length=120), nullable=False),
    sa.Column('device_type', sa.String(length=20), server_default=sa.text("'ios'"), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pull_cursor', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("device_type IN ('ios','web','android','other')", name=op.f('ck_user_devices_device_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_devices')),
    sa.UniqueConstraint('user_id', 'device_identifier', name=op.f('uq_user_devices_user_id_device_identifier'))
    )
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_dsa_count', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('daily_revision_count', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('include_lld_daily', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('include_hld_daily', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('daily_plan_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ai_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_auto_reveal_solution', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('preferred_languages', postgresql.ARRAY(sa.String(length=30)), server_default=sa.text("'{python}'::varchar[]"), nullable=False),
    sa.Column('theme', sa.String(length=20), server_default=sa.text("'system'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_index('ix_user_settings_user_id_updated_at', 'user_settings', ['user_id', 'updated_at'], unique=False)
    op.create_table('ai_messages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=True),
    sa.Column('selected_code', sa.Text(), nullable=True),
    sa.Column('snippet_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('system','user','assistant')", name=op.f('ck_ai_messages_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    op.create_index('ix_ai_messages_conversation_id_created_at', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_user_id'), 'ai_messages', ['user_id'], unique=False)
    op.create_index('ix_ai_messages_user_id_created_at', 'ai_messages', ['user_id', 'created_at'], unique=False)
    op.create_table('daily_plan_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('problem_id', sa.String(length=300), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("item_type IN ('dsa_new','dsa_revision','lld','hld')", name=op.f('ck_daily_plan_items_item_type_valid')),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_plans.id'], name=op.f('fk_daily_plan_items_plan_id_daily_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['dsa_problems.id'], name=op.f('fk_daily_plan_items_problem_id_dsa_problems'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_plan_items')),
    sa.UniqueConstraint('plan_id', 'item_type', 'problem_id', name=op.f('uq_daily_plan_items_plan_id_item_type_problem_id'))
    )
    op.create_index(op.f('ix_daily_plan_items_plan_id'), 'daily_plan_items', ['plan_id'], unique=False)
    op.create_index('ix_daily_plan_items_plan_id_position', 'daily_plan_items', ['plan_id', 'position'], unique=False)
    op.create_index(op.f('ix_daily_plan_items_user_id'), 'daily_plan_items', ['user_id'], unique=False)
    op.create_index('ix_daily_plan_items_user_id_completed_at', 'daily_plan_items', ['user_id', 'completed_at'], unique=False)
    op.create_table('hld_notes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hld_topic_id', sa.UUID(), nullable=False),
    sa.Column('functional_requirements', sa.Text(), nullable=True),
    sa.Column('non_functional_requirements', sa.Text(), nullable=True),
    sa.Column('capacity_estimation', sa.Text(), nullable=True),
    sa.Column('apis', sa.Text(), nullable=True),
    sa.Column('data_model', sa.Text(), nullable=True),
    sa.Column('high_level_architecture', sa.Text(), nullable=True),
    sa.Column('database_choice', sa.Text(), nullable=True),
    sa.Column('caching', sa.Text(), nullable=True),
    sa.Column('queues', sa.Text(), nullable=True),
    sa.Column('scaling', sa.Text(), nullable=True),
    sa.Column('failure_handling', sa.Text(), nullable=True),
    sa.Column('tradeoffs', sa.Text(), nullable=True),
    sa.Column('final_notes', sa.Text(), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('mistakes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hld_topic_id'], ['hld_topics.id'], name=op.f('fk_hld_notes_hld_topic_id_hld_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hld_notes')),
    sa.UniqueConstraint('user_id', 'hld_topic_id', name=op.f('uq_hld_notes_user_id_hld_topic_id'))
    )
    op.create_index(op.f('ix_hld_notes_hld_topic_id'), 'hld_notes', ['hld_topic_id'], unique=False)
    op.create_index(op.f('ix_hld_notes_user_id'), 'hld_notes', ['user_id'], unique=False)
    op.create_index('ix_hld_notes_user_id_updated_at', 'hld_notes', ['user_id', 'updated_at'], unique=False)
    op.create_table('hld_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hld_topic_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=True),
    sa.Column('revision_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_revision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_time_spent_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('not_started','learning','completed','needs_revision','mastered')", name=op.f('ck_hld_progress_status_valid')),
    sa.CheckConstraint('confidence IS NULL OR (confidence BETWEEN 0 AND 5)', name=op.f('ck_hld_progress_confidence_range')),
    sa.ForeignKeyConstraint(['hld_topic_id'], ['hld_topics.id'], name=op.f('fk_hld_progress_hld_topic_id_hld_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hld_progress')),
    sa.UniqueConstraint('user_id', 'hld_topic_id', name=op.f('uq_hld_progress_user_id_hld_topic_id'))
    )
    op.create_index(op.f('ix_hld_progress_hld_topic_id'), 'hld_progress', ['hld_topic_id'], unique=False)
    op.create_index(op.f('ix_hld_progress_next_revision_at'), 'hld_progress', ['next_revision_at'], unique=False)
    op.create_index(op.f('ix_hld_progress_user_id'), 'hld_progress', ['user_id'], unique=False)
    op.create_index('ix_hld_progress_user_id_next_revision_at', 'hld_progress', ['user_id', 'next_revision_at'], unique=False)
    op.create_index('ix_hld_progress_user_id_status', 'hld_progress', ['user_id', 'status'], unique=False)
    op.create_index('ix_hld_progress_user_id_updated_at', 'hld_progress', ['user_id', 'updated_at'], unique=False)
    op.create_table('lld_notes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lld_topic_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('design_explanation', sa.Text(), nullable=True),
    sa.Column('class_responsibilities', sa.Text(), nullable=True),
    sa.Column('relationships', sa.Text(), nullable=True),
    sa.Column('design_notes', sa.Text(), nullable=True),
    sa.Column('mistakes', sa.Text(), nullable=True),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.Column('patterns_used', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('class_diagram', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lld_topic_id'], ['lld_topics.id'], name=op.f('fk_lld_notes_lld_topic_id_lld_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lld_notes')),
    sa.UniqueConstraint('user_id', 'lld_topic_id', name=op.f('uq_lld_notes_user_id_lld_topic_id'))
    )
    op.create_index(op.f('ix_lld_notes_lld_topic_id'), 'lld_notes', ['lld_topic_id'], unique=False)
    op.create_index(op.f('ix_lld_notes_user_id'), 'lld_notes', ['user_id'], unique=False)
    op.create_index('ix_lld_notes_user_id_updated_at', 'lld_notes', ['user_id', 'updated_at'], unique=False)
    op.create_table('lld_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lld_topic_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=True),
    sa.Column('revision_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_revision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_time_spent_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('not_started','learning','completed','needs_revision','mastered')", name=op.f('ck_lld_progress_status_valid')),
    sa.CheckConstraint('confidence IS NULL OR (confidence BETWEEN 0 AND 5)', name=op.f('ck_lld_progress_confidence_range')),
    sa.ForeignKeyConstraint(['lld_topic_id'], ['lld_topics.id'], name=op.f('fk_lld_progress_lld_topic_id_lld_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lld_progress')),
    sa.UniqueConstraint('user_id', 'lld_topic_id', name=op.f('uq_lld_progress_user_id_lld_topic_id'))
    )
    op.create_index(op.f('ix_lld_progress_lld_topic_id'), 'lld_progress', ['lld_topic_id'], unique=False)
    op.create_index(op.f('ix_lld_progress_next_revision_at'), 'lld_progress', ['next_revision_at'], unique=False)
    op.create_index(op.f('ix_lld_progress_user_id'), 'lld_progress', ['user_id'], unique=False)
    op.create_index('ix_lld_progress_user_id_next_revision_at', 'lld_progress', ['user_id', 'next_revision_at'], unique=False)
    op.create_index('ix_lld_progress_user_id_status', 'lld_progress', ['user_id', 'status'], unique=False)
    op.create_index('ix_lld_progress_user_id_updated_at', 'lld_progress', ['user_id', 'updated_at'], unique=False)
    op.create_table('revision_queue',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.String(length=300), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=40), server_default=sa.text("'scheduled_revision'"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('confidence_before', sa.SmallInteger(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reason IN ('low_confidence','failed_attempt','scheduled_revision','manual','long_time_since_review')", name=op.f('ck_revision_queue_reason_valid')),
    sa.ForeignKeyConstraint(['problem_id'], ['dsa_problems.id'], name=op.f('fk_revision_queue_problem_id_dsa_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revision_queue'))
    )
    op.create_index(op.f('ix_revision_queue_due_at'), 'revision_queue', ['due_at'], unique=False)
    op.create_index(op.f('ix_revision_queue_problem_id'), 'revision_queue', ['problem_id'], unique=False)
    op.create_index(op.f('ix_revision_queue_user_id'), 'revision_queue', ['user_id'], unique=False)
    op.create_index('ix_revision_queue_user_id_completed_due_at', 'revision_queue', ['user_id', 'completed', 'due_at'], unique=False)
    op.create_index('ix_revision_queue_user_id_problem_id', 'revision_queue', ['user_id', 'problem_id'], unique=False)
    op.create_index('ix_revision_queue_user_id_updated_at', 'revision_queue', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revision_queue_user_id_updated_at', table_name='revision_queue')
    op.drop_index('ix_revision_queue_user_id_problem_id', table_name='revision_queue')
    op.drop_index('ix_revision_queue_user_id_completed_due_at', table_name='revision_queue')
    op.drop_index(op.f('ix_revision_queue_user_id'), table_name='revision_queue')
    op.drop_index(op.f('ix_revision_queue_problem_id'), table_name='revision_queue')
    op.drop_index(op.f('ix_revision_queue_due_at'), table_name='revision_queue')
    op.drop_table('revision_queue')
    op.drop_index('ix_lld_progress_user_id_updated_at', table_name='lld_progress')
    op.drop_index('ix_lld_progress_user_id_status', table_name='lld_progress')
    op.drop_index('ix_lld_progress_user_id_next_revision_at', table_name='lld_progress')
    op.drop_index(op.f('ix_lld_progress_user_id'), table_name='lld_progress')
    op.drop_index(op.f('ix_lld_progress_next_revision_at'), table_name='lld_progress')
    op.drop_index(op.f('ix_lld_progress_lld_topic_id'), table_name='lld_progress')
    op.drop_table('lld_progress')
    op.drop_index('ix_lld_notes_user_id_updated_at', table_name='lld_notes')
    op.drop_index(op.f('ix_lld_notes_user_id'), table_name='lld_notes')
    op.drop_index(op.f('ix_lld_notes_lld_topic_id'), table_name='lld_notes')
    op.drop_table('lld_notes')
    op.drop_index('ix_hld_progress_user_id_updated_at', table_name='hld_progress')
    op.drop_index('ix_hld_progress_user_id_status', table_name='hld_progress')
    op.drop_index('ix_hld_progress_user_id_next_revision_at', table_name='hld_progress')
    op.drop_index(op.f('ix_hld_progress_user_id'), table_name='hld_progress')
    op.drop_index(op.f('ix_hld_progress_next_revision_at'), table_name='hld_progress')
    op.drop_index(op.f('ix_hld_progress_hld_topic_id'), table_name='hld_progress')
    op.drop_table('hld_progress')
    op.drop_index('ix_hld_notes_user_id_updated_at', table_name='hld_notes')
    op.drop_index(op.f('ix_hld_notes_user_id'), table_name='hld_notes')
    op.drop_index(op.f('ix_hld_notes_hld_topic_id'), table_name='hld_notes')
    op.drop_table('hld_notes')
    op.drop_index('ix_daily_plan_items_user_id_completed_at', table_name='daily_plan_items')
    op.drop_index(op.f('ix_daily_plan_items_user_id'), table_name='daily_plan_items')
    op.drop_index('ix_daily_plan_items_plan_id_position', table_name='daily_plan_items')
    op.drop_index(op.f('ix_daily_plan_items_plan_id'), table_name='daily_plan_items')
    op.drop_table('daily_plan_items')
    op.drop_index('ix_ai_messages_user_id_created_at', table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_user_id'), table_name='ai_messages')
    op.drop_index('ix_ai_messages_conversation_id_created_at', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_user_settings_user_id_updated_at', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index('ix_user_activity_days_user_id_activity_date', table_name='user_activity_days')
    op.drop_index(op.f('ix_user_activity_days_user_id'), table_name='user_activity_days')
    op.drop_table('user_activity_days')
    op.drop_index('ix_sync_mutations_user_id_created_at', table_name='sync_mutations')
    op.drop_table('sync_mutations')
    op.drop_index('ix_sync_changes_user_id_seq', table_name='sync_changes')
    op.drop_index('ix_sync_changes_user_id_entity', table_name='sync_changes')
    op.drop_table('sync_changes')
    op.drop_index('ix_problem_attempts_user_id_updated_at', table_name='problem_attempts')
    op.drop_index('ix_problem_attempts_user_id_problem_id_started_at', table_name='problem_attempts')
    op.drop_index(op.f('ix_problem_attempts_user_id'), table_name='problem_attempts')
    op.drop_index(op.f('ix_problem_attempts_problem_id'), table_name='problem_attempts')
    op.drop_table('problem_attempts')
    op.drop_index('ix_lld_topics_category_order_index', table_name='lld_topics')
    op.drop_table('lld_topics')
    op.drop_index('ix_hld_topics_category_order_index', table_name='hld_topics')
    op.drop_table('hld_topics')
    op.drop_table('dsa_topics')
    op.drop_index('ix_dsa_problems_slug', table_name='dsa_problems')
    op.drop_index('ix_dsa_problems_primary_topic_order_index', table_name='dsa_problems')
    op.drop_index('ix_dsa_problems_patterns_gin', table_name='dsa_problems', postgresql_using='gin')
    op.drop_index('ix_dsa_problems_difficulty_order_index', table_name='dsa_problems')
    op.drop_index('ix_dsa_problems_companies_gin', table_name='dsa_problems', postgresql_using='gin')
    op.drop_table('dsa_problems')
    op.drop_index('ix_ai_rate_limits_window_start', table_name='ai_rate_limits')
    op.drop_table('ai_rate_limits')
    op.drop_index('ix_ai_conversations_user_id_updated_at', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_user_id_context', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
